# Nome del workflow di Deployment Continuo
name: Deployment Continuo su Hugging Face

# Trigger: si avvia solo al completamento con successo del workflow CI
on:
  workflow_run:
    # Il nome qui deve corrispondere esattamente al 'name:' nel file ci.yml
    workflows: ["Continuous Integration"]
    types:
      - completed

# Definizione dei jobs
jobs:
  # Nome del job
  deploy_to_hf_space:
    # Condizione: esegui questo job solo se il workflow CI ha avuto successo
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    # Lista dei passaggi da eseguire
    steps:
      # 1. Scarica il codice dal repository
      - name: Checkout del codice
        uses: actions/checkout@v4
        with:
          # Assicurati di usare il codice esatto del commit che ha attivato la CI
          ref: ${{ github.event.workflow_run.head_sha }}

      # 2. Installa lo strumento per comunicare con Hugging Face
      - name: Installa Hugging Face Hub
        run: pip install -U huggingface_hub

      # 3. Esegue il login e carica i file nelle destinazioni corrette
      - name: Carica file su Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Eseguo il login a Hugging Face..."
          huggingface-cli login --token $HF_TOKEN
          
          echo "--- Caricamento dei file dell'applicazione ---"
          # Spostati nella cartella App e carica il suo contenuto ('.') nella root dello Space
          cd App
          huggingface-cli upload gioottolins/drug_classification_app . --repo-type=space --commit-message="Deploy app files [skip ci]"
          
          echo "--- Caricamento del modello ---"
          # Torna indietro alla cartella principale
          cd ..
          # Carica la cartella locale 'Model' in una cartella 'Model' nello Space
          huggingface-cli upload gioottolins/drug_classification_app Model/ --repo-type=space --commit-message="Deploy model file [skip ci]"