# 'name' è all'inizio della riga
name: Deployment Continuo su Hugging Face

# 'on' è all'inizio della riga, su una nuova linea
on:
  # 'workflow_run' è indentato sotto 'on'
  workflow_run:
    # 'workflows' e 'types' sono indentati sotto 'workflow_run'
    workflows: ["Continuous Integration"]
    types:
      - completed

# 'jobs' è all'inizio della riga
jobs:
  # 'deploy_to_hf_space' è indentato sotto 'jobs'
  deploy_to_hf_space:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    # 'steps' è indentato sotto 'deploy_to_hf_space'
    steps:
      # Ogni trattino '-' indica l'inizio di un nuovo passaggio ed è indentato sotto 'steps'
      - name: Checkout del codice
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Installa Hugging Face Hub
        run: pip install -U huggingface_hub

      - name: Carica file su Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli login --token $HF_TOKEN
          huggingface-cli upload gioottolins/drug_classification_app App/ --repo-type=space --path-in-repo=. --commit-message="Deploy app files"
          huggingface-cli upload gioottolins/drug_classification_app Model/ --repo-type=space --path-in-repo=Model --commit-message="Deploy model file"